### ISSUE TITLE
URL creation 

### ISSUE THREAD

**Issue by hjadeh** [diegoakel/GoogleHistoryParser#1]
Python 3.12.5
pip 24.2
tldextract-5.1.2

```
C:\Users\**redacted**>C:\Users\**redacted**\Desktop\main.py
Traceback (most recent call last):
  File "C:\Users\**redacted**\Desktop\main.py", line 32, in <module>
    toCSV(data)
  File "C:\Users\**redacted**\Desktop\main.py", line 17, in toCSV
    domain = tldextract.extract(item["url"])[1]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'ExtractResult' object is not subscriptable
```

Appears to be a result of 5.0.0 upgrade 2023.10.11 https://github.com/john-kurkowski/tldextract/blob/master/CHANGELOG.md
From the change notes: "This means no more iterating/indexing/slicing/unpacking the result object returned by this library. It is no longer a tuple. You must directly reference the fields you're interested in."

trying to fix it but I dont really know what Im doing

**Comment by diegoakel** [comment]
Hello, sorry just saw it. Yes it was done with a pretty old Python version. You are using the project for something?

**Comment by hjadeh** [comment]
No worries! I was looking for a batch way to parse a user's chrome history to then check the security/safety of the sites they visited by checking against something like [dmarc](https://dmarc.org/). Initially I was trying to do it once after a series of issues a family member had with popups that I was investigating, but realized it could also be an app/extension with a bit more work but I haven't been able to work on it yet.

**Comment by diegoakel** [comment]
i changed it to use urllib instead, hope it works for you now. an extension would be cool!
